# conda env create -f environment.yml
name: lume-model-dev
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pydantic>2.3
  - numpy
  - pyyaml
  - tensorflow
  - botorch

  # dev requirements
  - pytest
  - pre-commit
  - black

  # docs requirements
  - mkdocs
  - mkdocstrings
  - mkdocstrings-python
  - mkdocs-material
