site_name: lume-model
site_url: https://slaclab.github.io/lume-model
repo_url: https://github.com/slaclab/lume-model
nav:
  - Home: index.md
  - Variables: variables.md
  - Models: models.md
  - Utils: utils.md
theme: material
plugins:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          selection:
            inherited_members: false
            filters:
              - "!^_"  # exlude all members starting with _
              - "^__init__$"  # but always include __init__ modules and methods
          rendering:
            show_source: true
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
