{% set data = load_setup_py_data(setup_file='../setup.py', from_recipe_dir=True) %}

package:
  name: "lume-model"
  version: {{ data.get('version') }}

build:
  noarch: python
  number: 2

source:
  path: ..

requirements:
  host:
    - python
    - setuptools
    - pip
    - pydantic
  run:
    - python
    - pydantic
    - numpy
    - pyyaml

test:
  imports:
    - lume_model
  requires:
    - pytest
    - tensorflow
    - botorch
    - hypothesis
  commands:
    # all these commands are executed in the conda-recipe directory so to run the
    # tests we need to move out of this folder, run them and then move back into
    # it
    - cd ..
    - py.test --pyargs tests
    - cd conda-recipe

about:
  home: https://github.com/slaclab/lume-model
  license: SLAC Open
  license_family: OTHER
  license_file: LICENSE
  summary: Lume-model hosts the variable classes required for running LUME models.
  doc_url: https://slaclab.github.io/lume-model/
  dev_url: https://github.com/slaclab/lume-model
