{% set data = load_setup_py_data(setup_file='../setup.py', from_recipe_dir=True) %}

package:
  name: "lume-model"
  version: {{ data.get('version') }}

build:
  noarch: python
  number: 0

source:
  path: ..

requirements:
  host:
    - python
    - setuptools
    - pip
  run:
    - python
    - pydantic>=1.6.1,<1.8.2
    - numpy
    - pyyaml

test:
  imports:
    - lume_model
  requires:
    - pytest
  commands:
    - py.test --pyargs lume_model

about:
  home: https://github.com/slaclab/lume-model
  license: SLAC Open
  license_family: OTHER
  license_file: LICENSE
  summary: Lume-model hosts the variable classes required for running LUME models.
  doc_url: https://slaclab.github.io/lume-model/
  dev_url: https://github.com/slaclab/lume-model
