{% set data = load_setup_py_data(setup_file='../setup.py', from_recipe_dir=True) %}

package:
  name: "lume-model"
  version: {{ data.get('version') }}

build:
  noarch: python
  number: 0

source:
  path: ..


requirements:
  host:
    - python
    - setuptools
    - pip
  run:
    - python
    - pydantic
    - numpy
    - pyyaml

test:
  imports:
    - lume_model
  requires:
    - pytest
  commands:
    - pip install tensorflow
    - py.test --pyargs lume_model

about:
  home: https://github.com/slaclab/lume-model
  license: Apache License 2.0
  summary: Lume-model hosts the variable classes required for running LUME models.
