name: Build docs

on:
  push:
    branches:
      - master

jobs:
  build:
    if: ${{ github.repository == 'slaclab/lume-model' }}
    runs-on: ubuntu-latest
    name:  Build docs
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.9
          mamba-version: "*"
          channels: conda-forge
          activate-environment: lume-model-dev
          environment-file: dev-environment.yml
      - name: Build package
        shell: bash -l {0}
        run: |
          pip install -e .
      - name: Build docs
        shell: bash -l {0}
        run: |
          mkdocs build
          mkdocs gh-deploy --force
