name: Build lume-model

on:
  push:
    branches:
      - github-actions
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest]
        python-version: [3.7, 3.8, 3.9]

    name: Python ${{ matrix.python-version }}, ${{ matrix.os }} build
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.9
          mamba-version: "*"
          channels: conda-forge
          activate-environment: lume-model-dev
          environment-file: dev-environment.yml
      - name: Build package
        shell: bash -l {0}
        run: |
          pip install -e .
          py.test --pyargs .
      - name: Build package
        shell: bash -l {0}
        run: |
          mamba install conda-build
          mamba build -q conda-recipe --python=${{ matrix.python-version }} --output-folder bld-dir
