name: Build lume-model

on:
  push:
  pull_request:
    types: [opened, reopened]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        python-version: ["3.9"]

    name: Python ${{ matrix.python-version }}, ${{ matrix.os }} build
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
          miniforge-variant: Mambaforge
          channels: conda-forge
          activate-environment: lume-model-dev
          environment-file: dev-environment.yml

      - name: Install lume-model
        shell: bash -l {0}
        run: |
          pip install -e .

      - name: Run Tests
        shell: bash -l {0}
        run: |
          pytest -ra --pyargs tests

      - name: Build package
        shell: bash -l {0}
        run: |
          mamba install conda-build
          mamba build -q conda-recipe --python=${{ matrix.python-version }} --output-folder bld-dir
